  apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-capstone

  template:
    metadata:
      labels:
        app: devops-capstone

    spec:
      containers:
        - name: devops-capstone
          image: yuki982/devops-capstone:${BUILD_NUMBER}
          ports:
            - containerPort: 5000
